### PR TITLE
bump version 0.3.2-nightly

### PR DESCRIPTION
**Pull request by razvan**
## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)

### CODE REVIEW

**Review by fhennig — APPROVED** [review]
:ok_hand:

**Comment by teozkr** [comment]
Doing this here has the same tradeoffs as doing it for operator-rs (thought we had an issue discussing this somewhere, but can't seem to find it now...).

**Comment by fhennig** [comment]
I don't understand, what do you mean, the version bump? I think I'm out of the loop here

**Comment by razvan** [comment]
Yeah, will add an item on tomorrow's arch agenda. We need everyone to be aware of this.

**Comment by teozkr** [comment]
Yeah, bumping to `-nightly` for indev versions. We already know it's a nightly because we depend on a path or git branch rather than on a git tag (and this is visible whenever Cargo refers to the crate's version).

On the other hand, switching to a different version means that [`[patch]` clauses](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section) won't take effect until you run `cargo update` (which may also bring along other unintended upgrades).

**Review by teozkr — CHANGES_REQUESTED** [review]
Flagging this until tomorrow's arch meeting then

**Pull request closed without merging**
