### PR TITLE
Add writer for configuration files in Python

### PR DESCRIPTION
**Pull request by siegfriedweber**
## Description

Add writer for configuration files in Python

used for stackabletech/superset-operator#173

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)

### CODE REVIEW

**Comment by teozkr** [comment]
This seems.. dangerous. Is there any significant gain from doing this vs emitting the user's config in an inert data format (JSON?) and shipping a static "config file" that just loads that data file?

**Comment by siegfriedweber** [comment]
The implementation for the boolean and integer literals is not dangerous.

The string literals are only dangerous if the escaping is not implemented correctly.

The Python expressions are dangerous but also powerful. The operator can use them to easily add own configuration options:

```rust
    config.insert(
￼        SupersetConfigOptions::StatsLogger.to_string(),
￼        "StatsdStatsLogger(host='0.0.0.0', port=9125)".into(),
￼    );
```

Admittedly, this can also be achieved with a static string.

If the cluster configuration does not expose options of type "Python expression" then there is only a risk at the configuration overrides. The configuration overrides need to be expressive to be useful:

```yaml
configOverrides:
  superset_config.py:
    CSV_EXPORT: "{'encoding': 'utf-8'}"
    PREFERRED_DATABASES: |-
      [
          'PostgreSQL',
          'Presto',
          'MySQL',
          'SQLite',
          # etc.
      ]
```

I do not see how this can be (easily) achieved with a JSON file without embedded Python code.

If the user installs a F.A.B. application directly, she/he is able to do (dangerous) configurations in the Python file. In my opinion, the operators should not restrict the possibilities of the products too much, otherwise the operators could be perceived as a burden. Furthermore, an administrator who knows how to configure e.g. Superset, will have no problems to configure it in the cluster spec if it resembles the product configuration as close as possible (which means Python code).

But I see your point and we should discuss, e.g. in the architecture meeting, if the operators should tend to flexibility or safety in such a case.

**Review by sbernauer — APPROVED** [review]
I looked through it with my limited Rust knowledge and liked it. Actually i learned new things in Rust.

**Comment by siegfriedweber** [comment]
bors merge

**Pull request merged**
