### PR TITLE
Adds bors & some minor actions cleanup

### PR DESCRIPTION
**Pull request by soenkeliebau**
- Added bors config to repo
- Removed clean step from test run to improve caching
- Added cache action to clippy job

## Review Checklist
- [x] Code contains useful comments
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)

### CODE REVIEW

**Review by teozkr — APPROVED** [review]

**Comment by soenkeliebau** [comment]
bors try

**Pull request merged**
